services:
  db:
    image: public.ecr.aws/docker/library/mysql:8.0.32
    environment:
      MYSQL_ROOT_PASSWORD: "test"
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

  app:
    tty: true
    image: mcr.microsoft.com/devcontainers/ruby:1-3.3-bullseye
    volumes:
      - ..:/workspace
    working_dir: /workspace
    environment:
      MYSQL_USER: test
      MYSQL_PASSWORD: test
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    links:
      - db
    ports:
      - 3300:3300

volumes:
  db_data:
